require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Category = require('../models/Category');
const Product = require('../models/Product');

const SAMPLE_PRODUCTS = [
    // ========== MEN'S SECTION ==========
    
    // MEN'S T-SHIRTS (5 products)
    {
        name: 'Essential White Tee',
        gender: 'men',
        subcategory: 't-shirts',
        price: 499,
        originalPrice: 799,
        rating: 4.4,
        numReviews: 201,
        isFeatured: true,
        brand: 'BasicCo',
        material: '180gsm Cotton',
        colors: ['White', 'Black', 'Grey'],
        sizes: [{ size: 'S', stock: 20 }, { size: 'M', stock: 25 }, { size: 'L', stock: 18 }, { size: 'XL', stock: 10 }],
        tags: ['essential', 'basic'],
        description: 'The perfect everyday white t-shirt — heavyweight cotton, clean cut.',
        images: [{ url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Slim Fit Graphic Tee',
        gender: 'men',
        subcategory: 't-shirts',
        price: 599,
        originalPrice: 899,
        rating: 4.2,
        numReviews: 89,
        isFeatured: false,
        brand: 'UrbanEdge',
        material: '100% Cotton',
        colors: ['Black', 'Grey'],
        sizes: [{ size: 'XS', stock: 5 }, { size: 'S', stock: 12 }, { size: 'M', stock: 18 }, { size: 'L', stock: 10 }],
        tags: ['casual', 'streetwear'],
        description: 'Comfortable slim-fit graphic print t-shirt for everyday wear.',
        images: [{ url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Oversized Streetwear Tee',
        gender: 'men',
        subcategory: 't-shirts',
        price: 699,
        originalPrice: 999,
        rating: 4.0,
        numReviews: 63,
        isFeatured: false,
        brand: 'DropShoulder',
        material: '100% Cotton',
        colors: ['Cream', 'Washed Black'],
        sizes: [{ size: 'S', stock: 8 }, { size: 'M', stock: 15 }, { size: 'L', stock: 12 }, { size: 'XL', stock: 9 }],
        tags: ['streetwear', 'oversized'],
        description: 'Boxy oversized tee with dropped shoulder for the modern look.',
        images: [{ url: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'V-Neck Premium Tee',
        gender: 'men',
        subcategory: 't-shirts',
        price: 549,
        originalPrice: 849,
        rating: 4.3,
        numReviews: 112,
        isFeatured: true,
        brand: 'Premium Basics',
        material: 'Combed Cotton',
        colors: ['Navy', 'Maroon', 'Olive'],
        sizes: [{ size: 'S', stock: 15 }, { size: 'M', stock: 22 }, { size: 'L', stock: 18 }, { size: 'XL', stock: 12 }],
        tags: ['premium', 'casual'],
        description: 'Sophisticated V-neck tee in premium combed cotton.',
        images: [{ url: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Striped Casual Tee',
        gender: 'men',
        subcategory: 't-shirts',
        price: 649,
        originalPrice: 999,
        rating: 4.1,
        numReviews: 87,
        isFeatured: false,
        brand: 'StripeStyle',
        material: '100% Cotton',
        colors: ['Blue Stripe', 'Red Stripe', 'Green Stripe'],
        sizes: [{ size: 'M', stock: 20 }, { size: 'L', stock: 25 }, { size: 'XL', stock: 15 }],
        tags: ['casual', 'striped'],
        description: 'Classic striped tee for a timeless casual look.',
        images: [{ url: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800', isMain: true }],
        tryOnSupported: true,
    },

    // MEN'S SHIRTS (5 products)
    {
        name: 'Oxford Button-Down Shirt',
        gender: 'men',
        subcategory: 'shirts',
        price: 1299,
        originalPrice: 1999,
        rating: 4.6,
        numReviews: 156,
        isFeatured: true,
        brand: 'Formal Plus',
        material: 'Oxford Cotton',
        colors: ['White', 'Light Blue', 'Pink'],
        sizes: [{ size: 'M', stock: 18 }, { size: 'L', stock: 22 }, { size: 'XL', stock: 15 }, { size: 'XXL', stock: 10 }],
        tags: ['formal', 'office'],
        description: 'Classic Oxford shirt perfect for office and formal occasions.',
        images: [{ url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Linen Summer Shirt',
        gender: 'men',
        subcategory: 'shirts',
        price: 1499,
        originalPrice: 2299,
        rating: 4.5,
        numReviews: 134,
        isFeatured: true,
        brand: 'LinenLife',
        material: '100% Linen',
        colors: ['Beige', 'White', 'Sky Blue'],
        sizes: [{ size: 'S', stock: 12 }, { size: 'M', stock: 20 }, { size: 'L', stock: 18 }, { size: 'XL', stock: 10 }],
        tags: ['summer', 'casual', 'linen'],
        description: 'Breathable linen shirt for hot summer days.',
        images: [{ url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Denim Casual Shirt',
        gender: 'men',
        subcategory: 'shirts',
        price: 1199,
        originalPrice: 1799,
        rating: 4.4,
        numReviews: 98,
        isFeatured: false,
        brand: 'DenimCraft',
        material: 'Denim',
        colors: ['Light Denim', 'Dark Denim'],
        sizes: [{ size: 'M', stock: 15 }, { size: 'L', stock: 20 }, { size: 'XL', stock: 12 }],
        tags: ['casual', 'denim'],
        description: 'Rugged denim shirt for a casual, stylish look.',
        images: [{ url: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Flannel Check Shirt',
        gender: 'men',
        subcategory: 'shirts',
        price: 1099,
        originalPrice: 1699,
        rating: 4.3,
        numReviews: 76,
        isFeatured: false,
        brand: 'WoodLand',
        material: 'Flannel',
        colors: ['Red Check', 'Blue Check', 'Green Check'],
        sizes: [{ size: 'M', stock: 18 }, { size: 'L', stock: 22 }, { size: 'XL', stock: 14 }],
        tags: ['casual', 'winter', 'flannel'],
        description: 'Cozy flannel shirt with classic check pattern.',
        images: [{ url: 'https://images.unsplash.com/photo-1642764873654-9eef0467b342?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YmVzdCUyMGNoZWNrcyUyMHNoaXJ0JTIwbWVufGVufDB8fDB8fHww', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Slim Fit Formal Shirt',
        gender: 'men',
        subcategory: 'shirts',
        price: 1399,
        originalPrice: 2099,
        rating: 4.7,
        numReviews: 189,
        isFeatured: true,
        brand: 'SlimFit Pro',
        material: 'Premium Cotton',
        colors: ['White', 'Black', 'Navy'],
        sizes: [{ size: 'S', stock: 10 }, { size: 'M', stock: 25 }, { size: 'L', stock: 20 }, { size: 'XL', stock: 15 }],
        tags: ['formal', 'slim-fit'],
        description: 'Modern slim-fit formal shirt for a sharp look.',
        images: [{ url: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=800', isMain: true }],
        tryOnSupported: true,
    },

    // MEN'S PANTS (5 products)
    {
        name: 'Classic Chino Pants',
        gender: 'men',
        subcategory: 'pants',
        price: 1799,
        originalPrice: 2499,
        rating: 4.5,
        numReviews: 167,
        isFeatured: true,
        brand: 'ChinoKing',
        material: 'Cotton Twill',
        colors: ['Khaki', 'Navy', 'Black', 'Grey'],
        sizes: [{ size: '30', stock: 15 }, { size: '32', stock: 25 }, { size: '34', stock: 20 }, { size: '36', stock: 12 }],
        tags: ['casual', 'chino'],
        description: 'Versatile chino pants for casual and semi-formal wear.',
        images: [{ url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Slim Fit Jeans',
        gender: 'men',
        subcategory: 'pants',
        price: 1999,
        originalPrice: 2999,
        rating: 4.6,
        numReviews: 234,
        isFeatured: true,
        brand: 'JeansCo',
        material: 'Stretch Denim',
        colors: ['Dark Blue', 'Black', 'Light Blue'],
        sizes: [{ size: '30', stock: 18 }, { size: '32', stock: 28 }, { size: '34', stock: 22 }, { size: '36', stock: 15 }],
        tags: ['denim', 'casual'],
        description: 'Modern slim-fit jeans with stretch for comfort.',
        images: [{ url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Formal Trousers',
        gender: 'men',
        subcategory: 'pants',
        price: 2199,
        originalPrice: 3299,
        rating: 4.7,
        numReviews: 198,
        isFeatured: true,
        brand: 'FormalWear',
        material: 'Wool Blend',
        colors: ['Black', 'Charcoal', 'Navy'],
        sizes: [{ size: '30', stock: 12 }, { size: '32', stock: 22 }, { size: '34', stock: 18 }, { size: '36', stock: 14 }],
        tags: ['formal', 'office'],
        description: 'Premium formal trousers for professional settings.',
        images: [{ url: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Cargo Pants',
        gender: 'men',
        subcategory: 'pants',
        price: 1699,
        originalPrice: 2399,
        rating: 4.3,
        numReviews: 145,
        isFeatured: false,
        brand: 'Adventure',
        material: 'Cotton Canvas',
        colors: ['Olive', 'Khaki', 'Black'],
        sizes: [{ size: '30', stock: 16 }, { size: '32', stock: 24 }, { size: '34', stock: 20 }, { size: '36', stock: 12 }],
        tags: ['casual', 'cargo'],
        description: 'Functional cargo pants with multiple pockets.',
        images: [{ url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Jogger Pants',
        gender: 'men',
        subcategory: 'pants',
        price: 1499,
        originalPrice: 2199,
        rating: 4.4,
        numReviews: 176,
        isFeatured: false,
        brand: 'ActiveFit',
        material: 'Cotton Blend',
        colors: ['Black', 'Grey', 'Navy'],
        sizes: [{ size: 'S', stock: 14 }, { size: 'M', stock: 26 }, { size: 'L', stock: 22 }, { size: 'XL', stock: 16 }],
        tags: ['casual', 'athleisure'],
        description: 'Comfortable jogger pants for casual and active wear.',
        images: [{ url: 'https://images.unsplash.com/photo-1555689502-c4b22d76c56f?w=800', isMain: true }],
        tryOnSupported: true,
    },

    // MEN'S SHOES (5 products)
    {
        name: 'Classic Leather Sneakers',
        gender: 'men',
        subcategory: 'shoes',
        price: 2499,
        originalPrice: 3499,
        rating: 4.6,
        numReviews: 203,
        isFeatured: true,
        brand: 'SneakerPro',
        material: 'Genuine Leather',
        colors: ['White', 'Black', 'Navy'],
        sizes: [{ size: '8', stock: 12 }, { size: '9', stock: 20 }, { size: '10', stock: 18 }, { size: '11', stock: 10 }],
        tags: ['casual', 'sneakers'],
        description: 'Premium leather sneakers for everyday wear.',
        images: [{ url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Formal Oxford Shoes',
        gender: 'men',
        subcategory: 'shoes',
        price: 3299,
        originalPrice: 4999,
        rating: 4.8,
        numReviews: 167,
        isFeatured: true,
        brand: 'FormalKing',
        material: 'Leather',
        colors: ['Black', 'Brown'],
        sizes: [{ size: '8', stock: 10 }, { size: '9', stock: 18 }, { size: '10', stock: 16 }, { size: '11', stock: 12 }],
        tags: ['formal', 'office'],
        description: 'Elegant Oxford shoes for formal occasions.',
        images: [{ url: 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Running Sports Shoes',
        gender: 'men',
        subcategory: 'shoes',
        price: 2799,
        originalPrice: 3999,
        rating: 4.5,
        numReviews: 289,
        isFeatured: true,
        brand: 'RunFast',
        material: 'Mesh & Synthetic',
        colors: ['Black-Red', 'Blue-White', 'Grey-Orange'],
        sizes: [{ size: '8', stock: 15 }, { size: '9', stock: 25 }, { size: '10', stock: 20 }, { size: '11', stock: 12 }],
        tags: ['sports', 'running'],
        description: 'Lightweight running shoes for optimal performance.',
        images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Canvas Casual Shoes',
        gender: 'men',
        subcategory: 'shoes',
        price: 1499,
        originalPrice: 2299,
        rating: 4.2,
        numReviews: 134,
        isFeatured: false,
        brand: 'CanvasWalk',
        material: 'Canvas',
        colors: ['Navy', 'Grey', 'Black'],
        sizes: [{ size: '8', stock: 18 }, { size: '9', stock: 22 }, { size: '10', stock: 16 }, { size: '11', stock: 10 }],
        tags: ['casual', 'canvas'],
        description: 'Comfortable canvas shoes for casual outings.',
        images: [{ url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Loafer Slip-On Shoes',
        gender: 'men',
        subcategory: 'shoes',
        price: 2199,
        originalPrice: 3299,
        rating: 4.4,
        numReviews: 156,
        isFeatured: false,
        brand: 'LoaferLux',
        material: 'Suede',
        colors: ['Brown', 'Black', 'Tan'],
        sizes: [{ size: '8', stock: 14 }, { size: '9', stock: 20 }, { size: '10', stock: 18 }, { size: '11', stock: 12 }],
        tags: ['casual', 'loafer'],
        description: 'Stylish slip-on loafers for smart casual look.',
        images: [{ url: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800', isMain: true }],
        tryOnSupported: true,
    },

    // MEN'S ACCESSORIES (5 products)
    {
        name: 'Leather Belt - Classic',
        gender: 'men',
        subcategory: 'accessories',
        price: 799,
        originalPrice: 1299,
        rating: 4.5,
        numReviews: 187,
        isFeatured: true,
        brand: 'BeltMaster',
        material: 'Genuine Leather',
        colors: ['Black', 'Brown', 'Tan'],
        sizes: [{ size: 'M', stock: 25 }, { size: 'L', stock: 30 }, { size: 'XL', stock: 20 }],
        tags: ['belt', 'leather'],
        description: 'Classic leather belt for formal and casual wear.',
        images: [{ url: 'https://images.unsplash.com/photo-1624222247344-550fb60583bb?w=800', isMain: true }],
        tryOnSupported: false,
    },
    {
        name: 'Leather Wallet',
        gender: 'men',
        subcategory: 'accessories',
        price: 999,
        originalPrice: 1599,
        rating: 4.7,
        numReviews: 234,
        isFeatured: true,
        brand: 'WalletPro',
        material: 'Leather',
        colors: ['Black', 'Brown'],
        sizes: [{ size: 'One Size', stock: 50 }],
        tags: ['wallet', 'leather'],
        description: 'Premium leather wallet with RFID protection.',
        images: [{ url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800', isMain: true }],
        tryOnSupported: false,
    },
    {
        name: 'Aviator Sunglasses',
        gender: 'men',
        subcategory: 'accessories',
        price: 1299,
        originalPrice: 1999,
        rating: 4.6,
        numReviews: 298,
        isFeatured: true,
        brand: 'ShadeStyle',
        material: 'Metal Frame',
        colors: ['Gold', 'Silver', 'Black'],
        sizes: [{ size: 'One Size', stock: 40 }],
        tags: ['sunglasses', 'aviator'],
        description: 'Classic aviator sunglasses with UV protection.',
        images: [{ url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800', isMain: true }],
        tryOnSupported: false,
    },
    {
        name: 'Analog Wrist Watch',
        gender: 'men',
        subcategory: 'accessories',
        price: 2999,
        originalPrice: 4999,
        rating: 4.8,
        numReviews: 412,
        isFeatured: true,
        brand: 'TimeKeeper',
        material: 'Stainless Steel',
        colors: ['Silver', 'Gold', 'Black'],
        sizes: [{ size: 'One Size', stock: 30 }],
        tags: ['watch', 'formal'],
        description: 'Elegant analog watch for sophisticated style.',
        images: [{ url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800', isMain: true }],
        tryOnSupported: false,
    },
    {
        name: 'Cotton Cap',
        gender: 'men',
        subcategory: 'accessories',
        price: 499,
        originalPrice: 799,
        rating: 4.3,
        numReviews: 156,
        isFeatured: false,
        brand: 'CapStyle',
        material: '100% Cotton',
        colors: ['Black', 'Navy', 'Grey', 'Olive'],
        sizes: [{ size: 'One Size', stock: 60 }],
        tags: ['cap', 'casual'],
        description: 'Casual cotton cap for everyday wear.',
        images: [{ url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800', isMain: true }],
        tryOnSupported: false,
    },

    // ========== WOMEN'S SECTION ==========
    
    // WOMEN'S DRESSES (5 products)
    {
        name: 'Floral Summer Dress',
        gender: 'women',
        subcategory: 'dresses',
        price: 1299,
        originalPrice: 1999,
        rating: 4.6,
        numReviews: 145,
        isFeatured: true,
        brand: 'FlowStyle',
        material: 'Cotton Blend',
        colors: ['Floral Pink', 'Floral Blue', 'Floral Yellow'],
        sizes: [{ size: 'XS', stock: 10 }, { size: 'S', stock: 20 }, { size: 'M', stock: 25 }, { size: 'L', stock: 15 }],
        tags: ['summer', 'floral', 'casual'],
        description: 'Light and breezy floral dress perfect for summer days.',
        images: [{ url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Little Black Dress',
        gender: 'women',
        subcategory: 'dresses',
        price: 1899,
        originalPrice: 2999,
        rating: 4.8,
        numReviews: 267,
        isFeatured: true,
        brand: 'ElegantWear',
        material: 'Polyester Blend',
        colors: ['Black'],
        sizes: [{ size: 'XS', stock: 12 }, { size: 'S', stock: 22 }, { size: 'M', stock: 28 }, { size: 'L', stock: 18 }],
        tags: ['formal', 'party', 'evening'],
        description: 'Timeless little black dress for any occasion.',
        images: [{ url: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Maxi Boho Dress',
        gender: 'women',
        subcategory: 'dresses',
        price: 1599,
        originalPrice: 2499,
        rating: 4.5,
        numReviews: 198,
        isFeatured: true,
        brand: 'BohoChic',
        material: 'Rayon',
        colors: ['Burgundy', 'Navy', 'Olive'],
        sizes: [{ size: 'S', stock: 18 }, { size: 'M', stock: 24 }, { size: 'L', stock: 20 }, { size: 'XL', stock: 12 }],
        tags: ['boho', 'maxi', 'casual'],
        description: 'Flowing maxi dress with bohemian vibes.',
        images: [{ url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Wrap Midi Dress',
        gender: 'women',
        subcategory: 'dresses',
        price: 1799,
        originalPrice: 2699,
        rating: 4.7,
        numReviews: 223,
        isFeatured: false,
        brand: 'WrapStyle',
        material: 'Satin',
        colors: ['Red', 'Emerald', 'Navy'],
        sizes: [{ size: 'XS', stock: 14 }, { size: 'S', stock: 20 }, { size: 'M', stock: 22 }, { size: 'L', stock: 16 }],
        tags: ['wrap', 'midi', 'elegant'],
        description: 'Flattering wrap midi dress for sophisticated style.',
        images: [{ url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'A-Line Cotton Dress',
        gender: 'women',
        subcategory: 'dresses',
        price: 1199,
        originalPrice: 1799,
        rating: 4.4,
        numReviews: 167,
        isFeatured: false,
        brand: 'CottonDream',
        material: '100% Cotton',
        colors: ['White', 'Coral', 'Mint'],
        sizes: [{ size: 'S', stock: 16 }, { size: 'M', stock: 26 }, { size: 'L', stock: 20 }, { size: 'XL', stock: 14 }],
        tags: ['casual', 'cotton', 'a-line'],
        description: 'Comfortable A-line dress in breathable cotton.',
        images: [{ url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800', isMain: true }],
        tryOnSupported: true,
    },

    // WOMEN'S TOPS (5 products)
    {
        name: 'Elegant Satin Top',
        gender: 'women',
        subcategory: 'tops',
        price: 899,
        originalPrice: 1499,
        rating: 4.3,
        numReviews: 78,
        isFeatured: true,
        brand: 'LuxeTops',
        material: 'Satin',
        colors: ['Champagne', 'Black', 'Navy'],
        sizes: [{ size: 'S', stock: 15 }, { size: 'M', stock: 20 }, { size: 'L', stock: 12 }, { size: 'XL', stock: 8 }],
        tags: ['elegant', 'party', 'formal'],
        description: 'Sophisticated satin top for evening occasions.',
        images: [{ url: 'https://images.unsplash.com/photo-1564257577-15ac8f94e1b0?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Casual Crop Top',
        gender: 'women',
        subcategory: 'tops',
        price: 599,
        originalPrice: 999,
        rating: 4.2,
        numReviews: 189,
        isFeatured: true,
        brand: 'TrendyTops',
        material: 'Cotton Blend',
        colors: ['White', 'Black', 'Pink', 'Lavender'],
        sizes: [{ size: 'XS', stock: 18 }, { size: 'S', stock: 25 }, { size: 'M', stock: 22 }, { size: 'L', stock: 15 }],
        tags: ['casual', 'crop', 'trendy'],
        description: 'Stylish crop top for casual summer days.',
        images: [{ url: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Silk Blouse',
        gender: 'women',
        subcategory: 'tops',
        price: 1299,
        originalPrice: 1999,
        rating: 4.6,
        numReviews: 145,
        isFeatured: true,
        brand: 'SilkLuxe',
        material: '100% Silk',
        colors: ['Ivory', 'Blush', 'Sage'],
        sizes: [{ size: 'S', stock: 12 }, { size: 'M', stock: 18 }, { size: 'L', stock: 14 }, { size: 'XL', stock: 10 }],
        tags: ['silk', 'formal', 'blouse'],
        description: 'Luxurious silk blouse for elegant occasions.',
        images: [{ url: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Off-Shoulder Top',
        gender: 'women',
        subcategory: 'tops',
        price: 799,
        originalPrice: 1299,
        rating: 4.4,
        numReviews: 234,
        isFeatured: false,
        brand: 'ShoulderStyle',
        material: 'Cotton Blend',
        colors: ['White', 'Red', 'Navy'],
        sizes: [{ size: 'XS', stock: 16 }, { size: 'S', stock: 24 }, { size: 'M', stock: 20 }, { size: 'L', stock: 12 }],
        tags: ['casual', 'off-shoulder', 'summer'],
        description: 'Chic off-shoulder top perfect for warm weather.',
        images: [{ url: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Peplum Top',
        gender: 'women',
        subcategory: 'tops',
        price: 999,
        originalPrice: 1599,
        rating: 4.5,
        numReviews: 167,
        isFeatured: false,
        brand: 'PeplumPerfect',
        material: 'Polyester',
        colors: ['Black', 'Burgundy', 'Emerald'],
        sizes: [{ size: 'S', stock: 14 }, { size: 'M', stock: 22 }, { size: 'L', stock: 18 }, { size: 'XL', stock: 12 }],
        tags: ['peplum', 'formal', 'elegant'],
        description: 'Flattering peplum top for a feminine silhouette.',
        images: [{ url: 'https://images.unsplash.com/photo-1562137369-1a1a0bc66744?w=800', isMain: true }],
        tryOnSupported: true,
    },

    // WOMEN'S JEANS (5 products)
    {
        name: 'High-Waist Skinny Jeans',
        gender: 'women',
        subcategory: 'jeans',
        price: 1799,
        originalPrice: 2699,
        rating: 4.7,
        numReviews: 312,
        isFeatured: true,
        brand: 'JeanQueen',
        material: 'Stretch Denim',
        colors: ['Dark Blue', 'Black', 'Light Blue'],
        sizes: [{ size: '26', stock: 18 }, { size: '28', stock: 26 }, { size: '30', stock: 22 }, { size: '32', stock: 16 }],
        tags: ['skinny', 'high-waist', 'denim'],
        description: 'Flattering high-waist skinny jeans with stretch.',
        images: [{ url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Mom Jeans',
        gender: 'women',
        subcategory: 'jeans',
        price: 1599,
        originalPrice: 2399,
        rating: 4.5,
        numReviews: 267,
        isFeatured: true,
        brand: 'RetroJeans',
        material: 'Denim',
        colors: ['Light Wash', 'Medium Wash', 'Dark Wash'],
        sizes: [{ size: '26', stock: 20 }, { size: '28', stock: 28 }, { size: '30', stock: 24 }, { size: '32', stock: 18 }],
        tags: ['mom-jeans', 'vintage', 'casual'],
        description: 'Trendy mom jeans with a relaxed fit.',
        images: [{ url: 'https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Boyfriend Jeans',
        gender: 'women',
        subcategory: 'jeans',
        price: 1699,
        originalPrice: 2499,
        rating: 4.4,
        numReviews: 198,
        isFeatured: false,
        brand: 'BoyfriendDenim',
        material: 'Cotton Denim',
        colors: ['Light Blue', 'Medium Blue'],
        sizes: [{ size: '26', stock: 16 }, { size: '28', stock: 24 }, { size: '30', stock: 20 }, { size: '32', stock: 14 }],
        tags: ['boyfriend', 'casual', 'relaxed'],
        description: 'Relaxed boyfriend jeans for a laid-back look.',
        images: [{ url: 'https://images.unsplash.com/photo-1582418702059-97ebafb35d09?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Flare Jeans',
        gender: 'women',
        subcategory: 'jeans',
        price: 1899,
        originalPrice: 2799,
        rating: 4.6,
        numReviews: 234,
        isFeatured: true,
        brand: 'FlareStyle',
        material: 'Stretch Denim',
        colors: ['Dark Blue', 'Black'],
        sizes: [{ size: '26', stock: 14 }, { size: '28', stock: 22 }, { size: '30', stock: 20 }, { size: '32', stock: 16 }],
        tags: ['flare', 'retro', 'bootcut'],
        description: 'Retro flare jeans for a vintage vibe.',
        images: [{ url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Ripped Skinny Jeans',
        gender: 'women',
        subcategory: 'jeans',
        price: 1999,
        originalPrice: 2999,
        rating: 4.3,
        numReviews: 289,
        isFeatured: false,
        brand: 'DistressedDenim',
        material: 'Stretch Denim',
        colors: ['Light Blue', 'Black'],
        sizes: [{ size: '26', stock: 18 }, { size: '28', stock: 26 }, { size: '30', stock: 22 }, { size: '32', stock: 14 }],
        tags: ['ripped', 'edgy', 'skinny'],
        description: 'Edgy ripped skinny jeans for a bold statement.',
        images: [{ url: 'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=800', isMain: true }],
        tryOnSupported: true,
    },

    // WOMEN'S SHOES (5 products)
    {
        name: 'Classic Heels',
        gender: 'women',
        subcategory: 'shoes',
        price: 2299,
        originalPrice: 3499,
        rating: 4.5,
        numReviews: 178,
        isFeatured: true,
        brand: 'HeelQueen',
        material: 'Synthetic',
        colors: ['Black', 'Nude', 'Red'],
        sizes: [{ size: '6', stock: 14 }, { size: '7', stock: 22 }, { size: '8', stock: 18 }, { size: '9', stock: 12 }],
        tags: ['heels', 'formal', 'party'],
        description: 'Elegant classic heels for formal occasions.',
        images: [{ url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Ankle Boots',
        gender: 'women',
        subcategory: 'shoes',
        price: 2799,
        originalPrice: 3999,
        rating: 4.6,
        numReviews: 234,
        isFeatured: true,
        brand: 'BootStyle',
        material: 'Leather',
        colors: ['Black', 'Brown', 'Tan'],
        sizes: [{ size: '6', stock: 16 }, { size: '7', stock: 24 }, { size: '8', stock: 20 }, { size: '9', stock: 14 }],
        tags: ['boots', 'ankle', 'casual'],
        description: 'Versatile ankle boots for everyday style.',
        images: [{ url: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Ballet Flats',
        gender: 'women',
        subcategory: 'shoes',
        price: 1499,
        originalPrice: 2299,
        rating: 4.4,
        numReviews: 298,
        isFeatured: true,
        brand: 'BalletWalk',
        material: 'Synthetic Leather',
        colors: ['Black', 'Nude', 'Navy', 'Red'],
        sizes: [{ size: '6', stock: 20 }, { size: '7', stock: 28 }, { size: '8', stock: 22 }, { size: '9', stock: 16 }],
        tags: ['flats', 'casual', 'comfort'],
        description: 'Comfortable ballet flats for all-day wear.',
        images: [{ url: 'https://images.unsplash.com/photo-1619994403073-5af2c50b8cf4?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Wedge Sandals',
        gender: 'women',
        subcategory: 'shoes',
        price: 1999,
        originalPrice: 2999,
        rating: 4.3,
        numReviews: 167,
        isFeatured: false,
        brand: 'WedgeStyle',
        material: 'Cork & Synthetic',
        colors: ['Tan', 'Black', 'White'],
        sizes: [{ size: '6', stock: 18 }, { size: '7', stock: 24 }, { size: '8', stock: 20 }, { size: '9', stock: 12 }],
        tags: ['wedge', 'sandals', 'summer'],
        description: 'Stylish wedge sandals perfect for summer.',
        images: [{ url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'White Sneakers',
        gender: 'women',
        subcategory: 'shoes',
        price: 1799,
        originalPrice: 2699,
        rating: 4.7,
        numReviews: 412,
        isFeatured: true,
        brand: 'SneakerChic',
        material: 'Synthetic Leather',
        colors: ['White', 'White-Gold', 'White-Silver'],
        sizes: [{ size: '6', stock: 22 }, { size: '7', stock: 30 }, { size: '8', stock: 26 }, { size: '9', stock: 18 }],
        tags: ['sneakers', 'casual', 'white'],
        description: 'Classic white sneakers for effortless style.',
        images: [{ url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800', isMain: true }],
        tryOnSupported: true,
    },

    // WOMEN'S ACCESSORIES (5 products)
    {
        name: 'Leather Handbag',
        gender: 'women',
        subcategory: 'accessories',
        price: 2999,
        originalPrice: 4499,
        rating: 4.8,
        numReviews: 298,
        isFeatured: true,
        brand: 'BagLuxe',
        material: 'Genuine Leather',
        colors: ['Black', 'Brown', 'Tan'],
        sizes: [{ size: 'One Size', stock: 40 }],
        tags: ['handbag', 'leather', 'luxury'],
        description: 'Premium leather handbag for sophisticated style.',
        images: [{ url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800', isMain: true }],
        tryOnSupported: false,
    },
    {
        name: 'Statement Necklace',
        gender: 'women',
        subcategory: 'accessories',
        price: 899,
        originalPrice: 1499,
        rating: 4.5,
        numReviews: 234,
        isFeatured: true,
        brand: 'JewelCraft',
        material: 'Metal & Stones',
        colors: ['Gold', 'Silver', 'Rose Gold'],
        sizes: [{ size: 'One Size', stock: 50 }],
        tags: ['necklace', 'jewelry', 'statement'],
        description: 'Bold statement necklace to elevate any outfit.',
        images: [{ url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800', isMain: true }],
        tryOnSupported: false,
    },
    {
        name: 'Designer Sunglasses',
        gender: 'women',
        subcategory: 'accessories',
        price: 1599,
        originalPrice: 2499,
        rating: 4.6,
        numReviews: 267,
        isFeatured: true,
        brand: 'SunStyle',
        material: 'Acetate Frame',
        colors: ['Black', 'Tortoise', 'Pink'],
        sizes: [{ size: 'One Size', stock: 45 }],
        tags: ['sunglasses', 'designer', 'fashion'],
        description: 'Chic designer sunglasses with UV protection.',
        images: [{ url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800', isMain: true }],
        tryOnSupported: false,
    },
    {
        name: 'Silk Scarf',
        gender: 'women',
        subcategory: 'accessories',
        price: 799,
        originalPrice: 1299,
        rating: 4.4,
        numReviews: 178,
        isFeatured: false,
        brand: 'SilkElegance',
        material: '100% Silk',
        colors: ['Floral', 'Abstract', 'Geometric'],
        sizes: [{ size: 'One Size', stock: 60 }],
        tags: ['scarf', 'silk', 'luxury'],
        description: 'Luxurious silk scarf for elegant styling.',
        images: [{ url: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800', isMain: true }],
        tryOnSupported: false,
    },
    {
        name: 'Watch - Ladies',
        gender: 'women',
        subcategory: 'accessories',
        price: 3499,
        originalPrice: 5499,
        rating: 4.7,
        numReviews: 345,
        isFeatured: true,
        brand: 'TimePiece',
        material: 'Stainless Steel',
        colors: ['Silver', 'Gold', 'Rose Gold'],
        sizes: [{ size: 'One Size', stock: 35 }],
        tags: ['watch', 'elegant', 'accessory'],
        description: 'Elegant ladies watch for timeless style.',
        images: [{ url: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800', isMain: true }],
        tryOnSupported: false,
    },

    // ========== CHILDREN'S SECTION ==========
    
    // CHILDREN'S BOYS (5 products)
    {
        name: 'Kids Superhero Graphic Tee',
        gender: 'children',
        subcategory: 'boys',
        price: 399,
        originalPrice: 599,
        rating: 4.7,
        numReviews: 120,
        isFeatured: true,
        brand: 'KidZone',
        material: '100% Soft Cotton',
        colors: ['Blue', 'Red', 'Black'],
        sizes: [{ size: '2-3Y', stock: 15 }, { size: '4-5Y', stock: 20 }, { size: '6-7Y', stock: 18 }, { size: '8-9Y', stock: 12 }],
        tags: ['boys', 'graphic', 'superhero', 'casual'],
        description: 'Cool superhero graphic tee that kids absolutely love! Soft cotton fabric.',
        images: [{ url: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Cool Denim Jacket - Kids',
        gender: 'children',
        subcategory: 'boys',
        price: 999,
        originalPrice: 1599,
        rating: 4.5,
        numReviews: 87,
        isFeatured: true,
        brand: 'DenimKids',
        material: 'Premium Denim',
        colors: ['Light Blue', 'Dark Blue'],
        sizes: [{ size: '4-5Y', stock: 10 }, { size: '6-7Y', stock: 15 }, { size: '8-9Y', stock: 12 }, { size: '10-11Y', stock: 8 }],
        tags: ['boys', 'jacket', 'denim', 'casual'],
        description: 'Stylish denim jacket for cool kids. Versatile and durable.',
        images: [{ url: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Sports Jersey Tee - Boys',
        gender: 'children',
        subcategory: 'boys',
        price: 449,
        originalPrice: 699,
        rating: 4.4,
        numReviews: 98,
        isFeatured: false,
        brand: 'ActiveKids',
        material: 'Quick-Dry Polyester',
        colors: ['Blue', 'Green', 'Red'],
        sizes: [{ size: '4-5Y', stock: 15 }, { size: '6-7Y', stock: 20 }, { size: '8-9Y', stock: 18 }, { size: '10-11Y', stock: 10 }],
        tags: ['boys', 'sports', 'active', 'jersey'],
        description: 'Breathable sports jersey for active kids. Perfect for playtime!',
        images: [{ url: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Striped Polo Shirt - Boys',
        gender: 'children',
        subcategory: 'boys',
        price: 549,
        originalPrice: 899,
        rating: 4.3,
        numReviews: 67,
        isFeatured: false,
        brand: 'SmartKids',
        material: 'Cotton Pique',
        colors: ['Navy Stripe', 'Red Stripe', 'Green Stripe'],
        sizes: [{ size: '4-5Y', stock: 12 }, { size: '6-7Y', stock: 18 }, { size: '8-9Y', stock: 15 }, { size: '10-11Y', stock: 10 }],
        tags: ['boys', 'polo', 'casual', 'smart'],
        description: 'Classic striped polo for smart casual occasions.',
        images: [{ url: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Cargo Shorts - Boys',
        gender: 'children',
        subcategory: 'boys',
        price: 599,
        originalPrice: 899,
        rating: 4.6,
        numReviews: 145,
        isFeatured: true,
        brand: 'AdventureKids',
        material: 'Cotton Canvas',
        colors: ['Khaki', 'Olive', 'Navy'],
        sizes: [{ size: '4-5Y', stock: 18 }, { size: '6-7Y', stock: 22 }, { size: '8-9Y', stock: 20 }, { size: '10-11Y', stock: 14 }],
        tags: ['boys', 'shorts', 'cargo', 'summer'],
        description: 'Comfortable cargo shorts with multiple pockets for adventure.',
        images: [{ url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800', isMain: true }],
        tryOnSupported: true,
    },

    // CHILDREN'S GIRLS (5 products)
    {
        name: 'Rainbow Unicorn Princess Dress',
        gender: 'children',
        subcategory: 'girls',
        price: 799,
        originalPrice: 1299,
        rating: 4.9,
        numReviews: 203,
        isFeatured: true,
        brand: 'PrincessWear',
        material: 'Soft Tulle & Cotton',
        colors: ['Pink', 'Purple', 'Rainbow'],
        sizes: [{ size: '2-3Y', stock: 12 }, { size: '4-5Y', stock: 22 }, { size: '6-7Y', stock: 20 }, { size: '8-9Y', stock: 15 }],
        tags: ['girls', 'princess', 'party', 'dress'],
        description: 'Magical unicorn princess dress with sparkly details. Perfect for parties!',
        images: [{ url: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Cute Floral Summer Dress - Girls',
        gender: 'children',
        subcategory: 'girls',
        price: 599,
        originalPrice: 899,
        rating: 4.6,
        numReviews: 156,
        isFeatured: true,
        brand: 'FlowerGirls',
        material: 'Breathable Cotton',
        colors: ['Yellow Floral', 'Pink Floral', 'Blue Floral'],
        sizes: [{ size: '2-3Y', stock: 18 }, { size: '4-5Y', stock: 25 }, { size: '6-7Y', stock: 20 }, { size: '8-9Y', stock: 12 }],
        tags: ['girls', 'summer', 'floral', 'casual'],
        description: 'Adorable floral dress for sunny days. Light and comfortable.',
        images: [{ url: 'https://images.unsplash.com/photo-1621452773781-0f992fd1f5cb?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Ballerina Tutu Skirt - Girls',
        gender: 'children',
        subcategory: 'girls',
        price: 499,
        originalPrice: 799,
        rating: 4.8,
        numReviews: 175,
        isFeatured: false,
        brand: 'DanceDreams',
        material: 'Soft Tulle',
        colors: ['Pink', 'White', 'Lavender'],
        sizes: [{ size: '2-3Y', stock: 20 }, { size: '4-5Y', stock: 25 }, { size: '6-7Y', stock: 22 }, { size: '8-9Y', stock: 15 }],
        tags: ['girls', 'tutu', 'dance', 'party'],
        description: 'Dreamy tutu skirt for little dancers. Fluffy and twirl-worthy!',
        images: [{ url: 'https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Denim Skirt - Girls',
        gender: 'children',
        subcategory: 'girls',
        price: 649,
        originalPrice: 999,
        rating: 4.5,
        numReviews: 134,
        isFeatured: false,
        brand: 'DenimGirls',
        material: 'Soft Denim',
        colors: ['Light Blue', 'Dark Blue'],
        sizes: [{ size: '4-5Y', stock: 16 }, { size: '6-7Y', stock: 22 }, { size: '8-9Y', stock: 18 }, { size: '10-11Y', stock: 12 }],
        tags: ['girls', 'denim', 'skirt', 'casual'],
        description: 'Cute denim skirt for everyday wear.',
        images: [{ url: 'https://images.unsplash.com/photo-1509319117482-b7d493ab7655?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Graphic Tee - Girls',
        gender: 'children',
        subcategory: 'girls',
        price: 399,
        originalPrice: 599,
        rating: 4.4,
        numReviews: 189,
        isFeatured: true,
        brand: 'GirlPower',
        material: '100% Cotton',
        colors: ['Pink', 'Purple', 'Mint'],
        sizes: [{ size: '2-3Y', stock: 20 }, { size: '4-5Y', stock: 26 }, { size: '6-7Y', stock: 22 }, { size: '8-9Y', stock: 16 }],
        tags: ['girls', 'graphic', 'casual', 'tee'],
        description: 'Fun graphic tee with cute designs kids love.',
        images: [{ url: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800', isMain: true }],
        tryOnSupported: true,
    },

    // CHILDREN'S BABY (5 products)
    {
        name: 'Comfy Baby Romper Set',
        gender: 'children',
        subcategory: 'baby',
        price: 599,
        originalPrice: 899,
        rating: 4.9,
        numReviews: 234,
        isFeatured: true,
        brand: 'BabyBliss',
        material: '100% Organic Cotton',
        colors: ['Mint Green', 'Baby Blue', 'Soft Pink'],
        sizes: [{ size: '0-3M', stock: 25 }, { size: '3-6M', stock: 30 }, { size: '6-12M', stock: 20 }, { size: '12-18M', stock: 15 }],
        tags: ['baby', 'romper', 'organic', 'comfort'],
        description: 'Soft organic cotton romper for babies. Gentle on delicate skin.',
        images: [{ url: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Baby Onesie 3-Pack',
        gender: 'children',
        subcategory: 'baby',
        price: 799,
        originalPrice: 1199,
        rating: 4.8,
        numReviews: 312,
        isFeatured: true,
        brand: 'BabyEssentials',
        material: '100% Cotton',
        colors: ['Pastel Mix', 'Primary Colors', 'Neutral Tones'],
        sizes: [{ size: '0-3M', stock: 30 }, { size: '3-6M', stock: 35 }, { size: '6-12M', stock: 25 }, { size: '12-18M', stock: 20 }],
        tags: ['baby', 'onesie', 'essential', 'value'],
        description: 'Value pack of 3 soft cotton onesies for everyday wear.',
        images: [{ url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Baby Sleep Suit',
        gender: 'children',
        subcategory: 'baby',
        price: 699,
        originalPrice: 999,
        rating: 4.7,
        numReviews: 267,
        isFeatured: true,
        brand: 'SleepyBaby',
        material: 'Soft Fleece',
        colors: ['White', 'Pink', 'Blue'],
        sizes: [{ size: '0-3M', stock: 22 }, { size: '3-6M', stock: 28 }, { size: '6-12M', stock: 24 }, { size: '12-18M', stock: 18 }],
        tags: ['baby', 'sleepwear', 'comfort', 'warm'],
        description: 'Cozy fleece sleep suit to keep baby warm and comfortable.',
        images: [{ url: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Baby Dress - Formal',
        gender: 'children',
        subcategory: 'baby',
        price: 899,
        originalPrice: 1399,
        rating: 4.6,
        numReviews: 189,
        isFeatured: false,
        brand: 'BabyFormal',
        material: 'Satin & Tulle',
        colors: ['White', 'Pink', 'Cream'],
        sizes: [{ size: '0-3M', stock: 15 }, { size: '3-6M', stock: 20 }, { size: '6-12M', stock: 18 }, { size: '12-18M', stock: 14 }],
        tags: ['baby', 'dress', 'formal', 'special occasion'],
        description: 'Adorable formal dress for special occasions and photos.',
        images: [{ url: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Baby T-Shirt Set',
        gender: 'children',
        subcategory: 'baby',
        price: 549,
        originalPrice: 849,
        rating: 4.5,
        numReviews: 145,
        isFeatured: false,
        brand: 'TinyTees',
        material: 'Soft Cotton',
        colors: ['Multicolor Pack'],
        sizes: [{ size: '0-3M', stock: 28 }, { size: '3-6M', stock: 32 }, { size: '6-12M', stock: 26 }, { size: '12-18M', stock: 20 }],
        tags: ['baby', 'tshirt', 'casual', 'everyday'],
        description: 'Set of colorful soft cotton t-shirts for daily wear.',
        images: [{ url: 'https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800', isMain: true }],
        tryOnSupported: true,
    },

    // CHILDREN'S SHOES (5 products)
    {
        name: 'Kids Running Shoes',
        gender: 'children',
        subcategory: 'shoes',
        price: 1299,
        originalPrice: 1899,
        rating: 4.7,
        numReviews: 234,
        isFeatured: true,
        brand: 'KidRunner',
        material: 'Mesh & Rubber',
        colors: ['Blue', 'Pink', 'Black'],
        sizes: [{ size: '10', stock: 18 }, { size: '11', stock: 22 }, { size: '12', stock: 20 }, { size: '13', stock: 16 }],
        tags: ['kids', 'sports', 'running', 'active'],
        description: 'Lightweight running shoes for active kids.',
        images: [{ url: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'School Shoes - Kids',
        gender: 'children',
        subcategory: 'shoes',
        price: 1499,
        originalPrice: 2199,
        rating: 4.6,
        numReviews: 298,
        isFeatured: true,
        brand: 'SchoolReady',
        material: 'Leather',
        colors: ['Black', 'Brown'],
        sizes: [{ size: '10', stock: 20 }, { size: '11', stock: 26 }, { size: '12', stock: 22 }, { size: '13', stock: 18 }],
        tags: ['kids', 'school', 'formal', 'durable'],
        description: 'Durable school shoes built to last all year.',
        images: [{ url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Velcro Sneakers - Kids',
        gender: 'children',
        subcategory: 'shoes',
        price: 999,
        originalPrice: 1499,
        rating: 4.5,
        numReviews: 267,
        isFeatured: true,
        brand: 'EasyWear',
        material: 'Synthetic',
        colors: ['Red', 'Blue', 'Pink'],
        sizes: [{ size: '8', stock: 16 }, { size: '9', stock: 24 }, { size: '10', stock: 22 }, { size: '11', stock: 18 }],
        tags: ['kids', 'velcro', 'easy', 'casual'],
        description: 'Easy velcro sneakers perfect for young kids.',
        images: [{ url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Rain Boots - Kids',
        gender: 'children',
        subcategory: 'shoes',
        price: 799,
        originalPrice: 1199,
        rating: 4.4,
        numReviews: 178,
        isFeatured: false,
        brand: 'RainyDays',
        material: 'Rubber',
        colors: ['Yellow', 'Red', 'Blue', 'Pink'],
        sizes: [{ size: '9', stock: 20 }, { size: '10', stock: 24 }, { size: '11', stock: 20 }, { size: '12', stock: 16 }],
        tags: ['kids', 'rain', 'boots', 'waterproof'],
        description: 'Fun rain boots to keep little feet dry and happy.',
        images: [{ url: 'https://images.unsplash.com/photo-1608667508764-33cf0726b13a?w=800', isMain: true }],
        tryOnSupported: true,
    },
    {
        name: 'Sandals - Kids Summer',
        gender: 'children',
        subcategory: 'shoes',
        price: 699,
        originalPrice: 999,
        rating: 4.3,
        numReviews: 145,
        isFeatured: false,
        brand: 'SummerFeet',
        material: 'EVA Foam',
        colors: ['Blue', 'Pink', 'Green'],
        sizes: [{ size: '8', stock: 22 }, { size: '9', stock: 26 }, { size: '10', stock: 24 }, { size: '11', stock: 18 }],
        tags: ['kids', 'sandals', 'summer', 'beach'],
        description: 'Comfortable summer sandals for beach and play.',
        images: [{ url: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800', isMain: true }],
        tryOnSupported: true,
    },
];

const seed = async () => {
    try {
        await connectDB();
        console.log('🌱 Seeding database with comprehensive product catalog...');

        // CLEAR EXISTING DATA
        await Category.deleteMany({});
        await Product.deleteMany({});
        console.log('✓ Cleared existing data');

        // ========== CREATE CATEGORIES ==========
        console.log('\n📁 Creating categories...');
        
        // Men's Categories
        const menCat = await Category.create({ name: 'Men', slug: 'men', gender: 'men', tryOnSupported: false });
        const menTshirtCat = await Category.create({ name: 'T-Shirts', slug: 'men-tshirts', gender: 'men', parent: menCat._id, tryOnSupported: true });
        const menShirtsCat = await Category.create({ name: 'Shirts', slug: 'men-shirts', gender: 'men', parent: menCat._id, tryOnSupported: true });
        const menPantsCat = await Category.create({ name: 'Pants', slug: 'men-pants', gender: 'men', parent: menCat._id, tryOnSupported: true });
        const menShoesCat = await Category.create({ name: 'Shoes', slug: 'men-shoes', gender: 'men', parent: menCat._id, tryOnSupported: true });
        const menAccessCat = await Category.create({ name: 'Accessories', slug: 'men-accessories', gender: 'men', parent: menCat._id, tryOnSupported: false });
        console.log('  ✓ Men\'s categories created');

        // Women's Categories
        const womenCat = await Category.create({ name: 'Women', slug: 'women', gender: 'women', tryOnSupported: false });
        const womenDressesCat = await Category.create({ name: 'Dresses', slug: 'women-dresses', gender: 'women', parent: womenCat._id, tryOnSupported: true });
        const womenTopsCat = await Category.create({ name: 'Tops', slug: 'women-tops', gender: 'women', parent: womenCat._id, tryOnSupported: true });
        const womenJeansCat = await Category.create({ name: 'Jeans', slug: 'women-jeans', gender: 'women', parent: womenCat._id, tryOnSupported: true });
        const womenShoesCat = await Category.create({ name: 'Shoes', slug: 'women-shoes', gender: 'women', parent: womenCat._id, tryOnSupported: true });
        const womenAccessCat = await Category.create({ name: 'Accessories', slug: 'women-accessories', gender: 'women', parent: womenCat._id, tryOnSupported: false });
        console.log('  ✓ Women\'s categories created');

        // Children's Categories
        const childrenCat = await Category.create({ name: 'Children', slug: 'children', gender: 'children', tryOnSupported: false });
        const childrenBoysCat = await Category.create({ name: 'Boys', slug: 'children-boys', gender: 'children', parent: childrenCat._id, tryOnSupported: true });
        const childrenGirlsCat = await Category.create({ name: 'Girls', slug: 'children-girls', gender: 'children', parent: childrenCat._id, tryOnSupported: true });
        const childrenBabyCat = await Category.create({ name: 'Baby', slug: 'children-baby', gender: 'children', parent: childrenCat._id, tryOnSupported: true });
        const childrenShoesCat = await Category.create({ name: 'Shoes', slug: 'children-shoes', gender: 'children', parent: childrenCat._id, tryOnSupported: true });
        console.log('  ✓ Children\'s categories created');

        // ========== CREATE PRODUCTS ==========
        console.log('\n📦 Creating products...');
        
        const categoryMap = {
            'men-t-shirts': menTshirtCat._id,
            'men-shirts': menShirtsCat._id,
            'men-pants': menPantsCat._id,
            'men-shoes': menShoesCat._id,
            'men-accessories': menAccessCat._id,
            'women-dresses': womenDressesCat._id,
            'women-tops': womenTopsCat._id,
            'women-jeans': womenJeansCat._id,
            'women-shoes': womenShoesCat._id,
            'women-accessories': womenAccessCat._id,
            'children-boys': childrenBoysCat._id,
            'children-girls': childrenGirlsCat._id,
            'children-baby': childrenBabyCat._id,
            'children-shoes': childrenShoesCat._id,
        };

        let createdCount = 0;
        const categoryCounts = {};

        for (const p of SAMPLE_PRODUCTS) {
            let categoryId;
            const key = `${p.gender}-${p.subcategory}`;
            categoryId = categoryMap[key];

            if (categoryId) {
                await Product.create({ ...p, category: categoryId });
                createdCount++;
                categoryCounts[key] = (categoryCounts[key] || 0) + 1;
            }
        }

        // ========== SUMMARY ==========
        const totalProducts = await Product.countDocuments();
        const menCount = await Product.countDocuments({ gender: 'men' });
        const womenCount = await Product.countDocuments({ gender: 'women' });
        const childrenCount = await Product.countDocuments({ gender: 'children' });
        const tryOnCount = await Product.countDocuments({ tryOnSupported: true });

        console.log('\n========================================');
        console.log('✅ DATABASE SEEDING COMPLETE!');
        console.log('========================================');
        console.log(`📦 Total Products: ${totalProducts}`);
        console.log(`\n👔 Men's Section: ${menCount} products`);
        console.log(`   - T-Shirts: ${categoryCounts['men-t-shirts'] || 0}`);
        console.log(`   - Shirts: ${categoryCounts['men-shirts'] || 0}`);
        console.log(`   - Pants: ${categoryCounts['men-pants'] || 0}`);
        console.log(`   - Shoes: ${categoryCounts['men-shoes'] || 0}`);
        console.log(`   - Accessories: ${categoryCounts['men-accessories'] || 0}`);
        console.log(`\n👗 Women's Section: ${womenCount} products`);
        console.log(`   - Dresses: ${categoryCounts['women-dresses'] || 0}`);
        console.log(`   - Tops: ${categoryCounts['women-tops'] || 0}`);
        console.log(`   - Jeans: ${categoryCounts['women-jeans'] || 0}`);
        console.log(`   - Shoes: ${categoryCounts['women-shoes'] || 0}`);
        console.log(`   - Accessories: ${categoryCounts['women-accessories'] || 0}`);
        console.log(`\n👶 Children's Section: ${childrenCount} products`);
        console.log(`   - Boys: ${categoryCounts['children-boys'] || 0}`);
        console.log(`   - Girls: ${categoryCounts['children-girls'] || 0}`);
        console.log(`   - Baby: ${categoryCounts['children-baby'] || 0}`);
        console.log(`   - Shoes: ${categoryCounts['children-shoes'] || 0}`);
        console.log(`\n✨ Products with Try-On: ${tryOnCount}`);
        console.log('========================================\n');
        console.log('🎉 Your fashion store is ready to go!');
        console.log('👉 Start your server and visit http://localhost:5173\n');

        process.exit(0);
    } catch (err) {
        console.error('❌ Seed error:', err.message);
        process.exit(1);
    }
};

seed();